name: First Pipeline
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: mv node_modules dist/
      - run: cp package.json dist/
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: webapp
          path: dist
  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: test-coverage
          path: coverage
  code_quality:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
  deploy:
    runs-on: ubuntu-22.04
    needs: code_quality
    steps:
      - uses: actions/download-artifact@v3.1.0
        with:
          name: webapp
      - name: Deploy to Azure web app
        uses: Azure/webapps-deploy@v2.2.19
        with:
          app-name: mygithubapp
          publish-profile:  
          
          
      
      
          
